### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by Shouheng88** [paul623/WebDavSyncerDemo#3]
无意间看到了文章然后看了下代码，顺便提点建议：
1. 异步任务没必要用 Thread，太重了，可以考虑 Kotlin 协程
2. 那个回调没必要搞 Looper 吧，新起的线程死循环了，Post 到主线程里就行了

**Comment by paul623** [comment]
looper那块示例代码是有点问题，当时主要是toast会报错，下个版本我修改一下~非常感谢

**Comment by paul623** [comment]
> 无意间看到了文章然后看了下代码，顺便提点建议：
> 
> 1. 异步任务没必要用 Thread，太重了，可以考虑 Kotlin 协程
> 2. 那个回调没必要搞 Looper 吧，新起的线程死循环了，Post 到主线程里就行了

looper那块示例代码是有点问题，当时主要是toast会报错，下个版本我修改一下~非常感谢
